spring:
 application:
  name: portfolio_back
 #rds-mysql세팅 
 datasource:
  hikari:
    driver-class-name: com.mysql.cj.jdbc.Driver
    jdbc-url: jdbc:mysql://mokkoji.c5a4em6e6j85.ap-northeast-2.rds.amazonaws.com:3306/mokkoji?autoReconnect=true&useUnicode=true&characterEncoding=utf-8
    username: mokkoji
    password: mokkoji123
   
#port
server:
 port: 80
 
#쿼리 로그 출력 레벨 설정
logging:
 level:
  org:
   hibernate:
    SQL: ERROR
    
#aws 접근키
cloud:
 aws:
  credntials:
   acessKey: AKIAW3MEBCBNXNAOHKEP
   secretKey: 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
  #s3 버킷정보
  s3:
   bucket: mokkoji
  region:
   static: ap-notheast-2
  stack:
   auto: false
